version: '3.3'

services:
  nginx-rtmp:
    image: nginx-rtmp
    container_name: nginx-rtmp
    build: .
    restart: always
    ports:
      - "1935:1935/tcp"
      - "8088:8088/tcp"
      - "8080:8080/tcp"
